# Generated by Django 3.1.3 on 2020-11-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='veiculos',
            new_name='Veiculo',
        ),
    ]
