# Generated by Django 3.1.3 on 2020-11-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_auto_20201119_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='valor',
            field=models.IntegerField(default=10000),
        ),
    ]
